#Partition Size (Hexadecimal, base 16)
BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x001800000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x001800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x0c0000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x65332f333 # 0x653333333 - 16384 (footer)
BOARD_CACHEIMAGE_PARTITION_SIZE    := 0x01b000000

BOARD_FLASH_BLOCK_SIZE := 131072

# Partitions types
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS:= true
BOARD_SUPPRESS_SECURE_ERASE := true
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD

# Recovery
ifeq ($(RECOVERY_VARIANT), twrp)
TW_DEVICE_VERSION := 1
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/devices/platform/gen-panel-backlight/backlight/panel/brightness"
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/11270000.usb3/musb-hdrc/gadget/lun0/file"
TW_MAX_BRIGHTNESS := 255
TW_MAX_BRIGHTNESS := 162
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := true
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_EXCLUDE_SUPERSU := true
TW_IGNORE_MISC_WIPE_DATA := true
TW_CRYPTO_USE_SYSTEM_VOLD := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_MTP_DEVICE := "/dev/mtp_usb"
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
endif
